/**
 * NovaSpark Bot v8.0 - FULL FLAT MEGA MENU
 * One message: image + full menu as caption. No sub-menus.
 * Owners: 263777124998 & 263786831091
 * By Dev-Ntando
 */
'use strict';
const config   = require('../../config');
const database = require('../../database');
module.exports = {
  name: 'menu',
  aliases: ['help', 'cmds', 'commands', 'start', 'h'],
  description: 'Full flat mega menu',
  category: 'free',
  execute: async ({ sock, msg, from, sender, args, reply }) => {
    const P      = config.prefix || '.';
    const isPrem = database.isPremium ? database.isPremium(sender) : false;
    const num    = sender.split('@')[0];
    const plan   = isPrem ? '\uD83D\uDCB8 Premium Member' : '\uD83C\uDD93 Free User';
    const uptime = process.uptime();
    const hrs    = Math.floor(uptime / 3600);
    const mins   = Math.floor((uptime % 3600) / 60);
    const secs   = Math.floor(uptime % 60);
    const upStr  = `${hrs}h ${mins}m ${secs}s`;
    const memMB  = Math.round(process.memoryUsage().heapUsed / 1024 / 1024);
    const memTot = Math.round(process.memoryUsage().heapTotal / 1024 / 1024);
    const now = new Date().toLocaleString('en-ZA', {
      timeZone: config.timezone || 'Africa/Harare',
      weekday: 'long', month: 'short', day: 'numeric',
      year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false,
    });
    const B = '\u2501'.repeat(35);
    const D = '\u2504'.repeat(35);
    const rows = [
      '\u2554' + '='.repeat(33) + '\u2557',
      '\u2551  \u26a1 NOVASPARK BOT v' + config.botVersion + ' \u26a1  \u2551',
      '\u2551  2026 Edition | Most Advanced WA Bot  \u2551',
      '\u255a' + '='.repeat(33) + '\u255d',
      '',
      '\ud83d\udc64 *+' + num + '*',
      '\ud83d\udccc ' + plan,
      '\ud83d\udd50 ' + now,
      '\u23f1\ufe0f Uptime: ' + upStr + '  \u00b7  \ud83d\udcbe ' + memMB + '/' + memTot + ' MB',
      B,
      '',
      '\ud83e\udd16 *A I   &   I N T E L L I G E N C E*',
      D,
      '  ' + P + 'gpt <msg>          \u2014 ChatGPT AI chat',
      '  ' + P + 'gemini <msg>       \u2014 Google Gemini AI',
      '  ' + P + 'character <n> <m>  \u2014 AI persona (luffy\u00b7naruto\u00b7batman)',
      '  ' + P + 'autochat on/off    \u2014 Auto AI replies',
      '  ' + P + 'imagine <prompt>   \u2014 AI image generation',
      '  ' + P + 'imagine2 <prompt>  \u2014 Alt AI image engine',
      '  ' + P + 'remini             \u2014 AI photo enhancer',
      '  ' + P + 'removebg           \u2014 Background remover',
      '  ' + P + 'genmusic <prompt>  \u2014 AI music generation',
      B,
      '',
      '\ud83d\udcda *S T U D Y   &   S C H O O L*',
      D,
      '  ' + P + 'homework <q>       \u2014 Answer homework questions',
      '  ' + P + 'essay <topic>      \u2014 Write full essay',
      '  ' + P + 'summarize <text>   \u2014 Summarize text/article',
      '  ' + P + 'studytips <subj>   \u2014 Study strategies',
      '  ' + P + 'math <problem>     \u2014 Solve math',
      '  ' + P + 'translate <l> <t>  \u2014 Translate any language',
      '  ' + P + 'pdf                \u2014 Generate PDF',
      B,
      '',
      '\ud83c\udfae *G A M E S   &   C H A L L E N G E S*',
      D,
      '  ' + P + 'wordle             \u2014 5-letter word guessing',
      '  ' + P + 'trivia             \u2014 Live trivia quiz',
      '  ' + P + 'hangman            \u2014 Classic hangman',
      '  ' + P + 'rps rock/paper/scissors',
      '  ' + P + '8ball <question>   \u2014 Magic 8-ball',
      '  ' + P + 'dice [N]  /  ' + P + 'flip  /  ' + P + 'roulette',
      '  ' + P + 'truth  /  ' + P + 'dare  /  ' + P + 'wouldyourather',
      '  ' + P + 'twotruth           \u2014 Two truths & a lie',
      '  ' + P + 'nhie               \u2014 Never Have I Ever \ud83c\udd95',
      B,
      '',
      '\ud83d\ude02 *F U N   &   S O C I A L*',
      D,
      '  ' + P + 'joke  /  ' + P + 'meme  /  ' + P + 'riddle',
      '  ' + P + 'roast @user  /  ' + P + 'insult @user',
      '  ' + P + 'flirt [@user]  /  ' + P + 'compliment [@user]',
      '  ' + P + 'ship @u1 @u2       \u2014 Love compatibility %',
      '  ' + P + 'couple @u1 @u2     \u2014 Couple name generator \ud83c\udd95',
      '  ' + P + 'vibe               \u2014 Vibe / spirit level check',
      '  ' + P + 'rate <anything>    \u2014 Rate anything /10 \ud83c\udd95',
      '  ' + P + 'zodiac <sign>      \u2014 Zodiac reading \ud83c\udd95',
      '  ' + P + 'horoscope <sign>   \u2014 Daily horoscope',
      '  ' + P + 'confess <msg>      \u2014 Anonymous confession \ud83c\udd95',
      '  ' + P + 'waifu  /  ' + P + 'gayrate [@user]',
      B,
      '',
      '\ud83d\udd27 *T O O L S   &   U T I L I T I E S*',
      D,
      '  ' + P + 'weather <city>     \u2014 Live weather forecast',
      '  ' + P + 'news [topic]       \u2014 Latest headlines',
      '  ' + P + 'qr <text>          \u2014 QR code generator',
      '  ' + P + 'calc <expr>        \u2014 Scientific calculator',
      '  ' + P + 'bmi <kg> <cm>  /  ' + P + 'age <date>',
      '  ' + P + 'time [zone]  /  ' + P + 'countdown <date>',
      '  ' + P + 'currency 100 USD ZAR',
      '  ' + P + 'convert <v> <f> <t>\u2014 Unit converter \ud83c\udd95',
      '  ' + P + 'color <hex/name>   \u2014 Color HEX/RGB/HSL \ud83c\udd95',
      '  ' + P + 'lyrics <song>      \u2014 Song lyrics \ud83c\udd95',
      '  ' + P + 'truthfact          \u2014 Mind-blowing fact \ud83c\udd95',
      '  ' + P + 'tts [lang] <text>  \u2014 Text-to-speech',
      '  ' + P + 'textart <s> <text> \u2014 ASCII art',
      '  ' + P + 'encode <t> <text>  \u2014 Encode base64/morse',
      '  ' + P + 'password [len]  /  ' + P + 'ip <addr>',
      '  ' + P + 'crypto <coin>  /  ' + P + 'shorturl <url>',
      '  ' + P + 'ssweb <url>  /  ' + P + 'define  /  ' + P + 'urban',
      '  ' + P + 'fact / ' + P + 'catfact / ' + P + 'dogfact / ' + P + 'numberfact <N>',
      '  ' + P + 'motivate / ' + P + 'advice / ' + P + 'quote',
      '  ' + P + 'getpp @user  /  ' + P + 'tempnumber  /  ' + P + 'myactivity',
      B,
      '',
      '\u2b07\ufe0f *D O W N L O A D S*',
      D,
      '  ' + P + 'ytmp3 <q/url>  \u2014 YouTube to MP3',
      '  ' + P + 'ytmp4 <q/url>  \u2014 YouTube to MP4',
      '  ' + P + 'tiktok / ' + P + 'instagram / ' + P + 'facebook / ' + P + 'pinterest',
      '  ' + P + 'spotify <query>\u2014 Spotify preview',
      B,
      '',
      '\ud83c\udfac *M E D I A   &   V I S U A L S*',
      D,
      '  ' + P + 'sticker  \u2014 Image/video to sticker',
      '  ' + P + 'simage <url>  /  ' + P + 'viewonce',
      '  ' + P + 'remini / ' + P + 'removebg \u2014 AI image tools',
      B,
      '',
      '\ud83d\udee1\ufe0f *G R O U P   M A N A G E M E N T*',
      D,
      '  ' + P + 'kick / ' + P + 'promote / ' + P + 'demote / ' + P + 'ban / ' + P + 'unban',
      '  ' + P + 'warn / ' + P + 'warns / ' + P + 'clearwarn / ' + P + 'listwarn \ud83c\udd95',
      '  ' + P + 'tagall / ' + P + 'hidetag / ' + P + 'tagadmins / ' + P + 'delete',
      '  ' + P + 'mute / ' + P + 'unmute / ' + P + 'grouplink / ' + P + 'resetlink',
      '  ' + P + 'welcome / ' + P + 'goodbye on/off',
      '  ' + P + 'setrules <rules> \ud83c\udd95  /  ' + P + 'rules \ud83c\udd95',
      '  ' + P + 'nightmode / ' + P + 'vip / ' + P + 'ghost on/off',
      '  ' + P + 'antilink / ' + P + 'antitoxic / ' + P + 'antiflood / ' + P + 'antiraid',
      '  ' + P + 'antiword / ' + P + 'antifwd / ' + P + 'antispam on/off',
      '  ' + P + 'autokick / ' + P + 'autoreact / ' + P + 'autoreply / ' + P + 'autonudge',
      '  ' + P + 'groupinfo / ' + P + 'groupstats / ' + P + 'membercount / ' + P + 'topmembers',
      B,
      '',
      '\u271d\ufe0f *F A I T H   &   I N S P I R A T I O N*',
      D,
      '  ' + P + 'tbj / ' + P + 'tbj <N> / ' + P + 'tbj search <topic>',
      '  ' + P + 'tbj quote / ' + P + 'tbj list',
      '  ' + P + 'bible <ref>  \u2014 KJV verse',
      '  ' + P + 'verse / ' + P + 'prayer / ' + P + 'pray <request>',
      '  ' + P + 'autoverse / ' + P + 'autoprayer / ' + P + 'autogm on HH:MM',
      B,
      '',
      '\u2699\ufe0f *A U T O   F E A T U R E S*',
      D,
      '  ' + P + 'autoonline / ' + P + 'autotyping / ' + P + 'autoread',
      '  ' + P + 'autoreply / ' + P + 'autostatus / ' + P + 'autobackup',
      '  ' + P + 'autoleave / ' + P + 'anticall / ' + P + 'antidelete',
      '  ' + P + 'waprotect / ' + P + 'pmblocker',
      B,
      '',
      '\ud83d\udcb8 *P R E M I U M*',
      D,
      '  ' + P + 'examprep <subject> \u2014 Exam prep',
      '  ' + P + 'code <lang> <task> \u2014 Code writer',
      '  ' + P + 'remind <time> <m>  \u2014 Smart reminder',
      '  ' + P + 'mystats / ' + P + 'setpersona / ' + P + 'autostudy',
      '  ' + P + 'upgrade            \u2014 Get Premium access',
      B,
      '',
      '\ud83d\udc51 *O W N E R   C O M M A N D S*',
      D,
      '  ' + P + 'shutdown / ' + P + 'restart \ud83c\udd95 / ' + P + 'botstats',
      '  ' + P + 'eval <code> \ud83c\udd95     \u2014 Run JavaScript',
      '  ' + P + 'broadcast / ' + P + 'announce / ' + P + 'dmowner',
      '  ' + P + 'setpremium add/rm/list',
      '  ' + P + 'ban / ' + P + 'unban / ' + P + 'banlist / ' + P + 'cleardb',
      '  ' + P + 'setprefix / ' + P + 'setprofile / ' + P + 'setnick \ud83c\udd95',
      '  ' + P + 'listgroups \ud83c\udd95 / ' + P + 'joingroup \ud83c\udd95 / ' + P + 'leavegroup \ud83c\udd95',
      '  ' + P + 'ownerlist \ud83c\udd95 / ' + P + 'addowner \ud83c\udd95 / ' + P + 'removeowner \ud83c\udd95',
      '  ' + P + 'maintenance on/off',
      B,
      '',
      '\ud83d\udce1 *' + config.botName + ' v' + config.botVersion + '*',
      '\ud83d\udc51 Owners: ' + (Array.isArray(config.ownerName) ? config.ownerName.join(' & ') : config.ownerName),
      '\ud83d\udccc Prefix: ' + P + '  \u00b7  \ud83c\udf0d TZ: ' + (config.timezone || 'Africa/Harare'),
      '',
      '_\ud83c\udd95 = New in v8.0  \u00b7  \ud83d\udcb8 = Premium only_',
      '_\u26a1 NovaSpark Bot \u2014 Built by Dev-Ntando_',
    ];
    const menuText = rows.join('\n');
    try {
      await sock.sendMessage(from, {
        image:   { url: 'https://i.imgur.com/4M7IWwP.jpeg' },
        caption: menuText,
      }, { quoted: msg });
    } catch {
      await sock.sendMessage(from, { text: menuText }, { quoted: msg });
    }
  },
};