/**
 * NovaSpark Bot — Project PDF Generator (Free)
 * .pdf <type> <title> | <subject> | <content>
 * Free: school project
 * Premium: CV, research paper, business plan, assignment, report
 */
'use strict';

const APIs     = require('../../utils/api');
const database = require('../../database');
const fs       = require('fs');
const path     = require('path');
const https    = require('https');
const http     = require('http');

// ── PDF HTML renderer (no external binary needed) ────────────────────────────
// We build an HTML string and use a free API to convert it
const buildHTML = (type, data, profile) => {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const studentName   = profile?.name   || 'Student';
  const studentSchool = profile?.school || 'School';
  const studentAge    = profile?.age    || '';

  const styles = `
    body { font-family: Arial, sans-serif; margin: 0; padding: 40px; color: #1a1a2e; }
    .cover { text-align: center; padding: 60px 20px; border-bottom: 3px solid #e94560; margin-bottom: 40px; }
    .cover h1 { font-size: 2.2em; color: #e94560; margin-bottom: 10px; }
    .cover h2 { font-size: 1.4em; color: #0f3460; margin: 8px 0; }
    .cover .meta { font-size: 1em; color: #555; margin-top: 20px; line-height: 1.8; }
    .cover .logo { font-size: 3em; margin-bottom: 20px; }
    h2 { color: #0f3460; border-left: 4px solid #e94560; padding-left: 12px; margin-top: 30px; }
    p { line-height: 1.8; font-size: 1.05em; }
    .footer { margin-top: 60px; text-align: center; color: #aaa; font-size: 0.85em; border-top: 1px solid #eee; padding-top: 20px; }
    ul { line-height: 2; }
    .badge { display: inline-block; background: #e94560; color: white; padding: 4px 12px; border-radius: 20px; font-size: 0.85em; margin: 4px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th { background: #0f3460; color: white; padding: 10px; text-align: left; }
    td { padding: 8px 10px; border-bottom: 1px solid #eee; }
    tr:nth-child(even) td { background: #f9f9f9; }
  `;

  let body = '';

  if (type === 'project' || type === 'assignment') {
    const sections = typeof data.content === 'string' ? data.content : '';
    body = `
      <div class="cover">
        <div class="logo">📋</div>
        <h1>${data.title}</h1>
        <h2>${data.subject}</h2>
        <div class="meta">
          <strong>Student:</strong> ${studentName}${studentAge ? ' (Age ' + studentAge + ')' : ''}<br>
          <strong>School:</strong> ${studentSchool}<br>
          <strong>Date:</strong> ${today}<br>
          <span class="badge">⚡ NovaSpark Bot</span>
        </div>
      </div>
      ${sections}
      <div class="footer">Generated by NovaSpark Bot ⚡ | Dev-Ntando | ${today}</div>
    `;
  } else if (type === 'cv' || type === 'resume') {
    body = `
      <div class="cover">
        <div class="logo">👤</div>
        <h1>${studentName}</h1>
        <h2>Curriculum Vitae</h2>
        <div class="meta">${studentSchool} | ${today}</div>
      </div>
      ${data.content}
      <div class="footer">Generated by NovaSpark Bot ⚡ | ${today}</div>
    `;
  } else if (type === 'report') {
    body = `
      <div class="cover">
        <div class="logo">📊</div>
        <h1>${data.title}</h1>
        <h2>Report</h2>
        <div class="meta">
          <strong>Prepared by:</strong> ${studentName}<br>
          <strong>Institution:</strong> ${studentSchool}<br>
          <strong>Date:</strong> ${today}
        </div>
      </div>
      ${data.content}
      <div class="footer">Generated by NovaSpark Bot ⚡ | ${today}</div>
    `;
  } else {
    body = `
      <div class="cover">
        <div class="logo">📄</div>
        <h1>${data.title}</h1>
        <div class="meta"><strong>By:</strong> ${studentName} | ${today}</div>
      </div>
      ${data.content}
      <div class="footer">Generated by NovaSpark Bot ⚡ | ${today}</div>
    `;
  }

  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><style>${styles}</style></head><body>${body}</body></html>`;
};

// ── Convert HTML to PDF via API ───────────────────────────────────────────────
const htmlToPdf = async (htmlContent) => {
  const axios = require('axios');
  // Use html2pdf API (free tier)
  try {
    const resp = await axios.post(
      'https://api.html2pdf.app/v1/generate',
      {
        html: htmlContent,
        apiKey: 'YXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5.eyJzdWIiOiJmcmVlX3VzZXIiLCJpYXQiOjE3MTQ1OTI4MDB9.free',
        landscape: false,
        paper: 'A4',
        scale: 1,
        marginTop: 0,
        marginBottom: 0,
      },
      { responseType: 'arraybuffer', timeout: 30000 }
    );
    if (resp.data && resp.data.byteLength > 500) return Buffer.from(resp.data);
  } catch { /* fall through */ }

  // Fallback: pdfshift free tier
  try {
    const resp = await axios.post(
      'https://api.pdfshift.io/v3/convert/pdf',
      { source: htmlContent, landscape: false, format: 'A4' },
      {
        auth: { username: 'api', password: 'sk_5b4c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c' },
        responseType: 'arraybuffer',
        timeout: 30000,
      }
    );
    if (resp.data && resp.data.byteLength > 500) return Buffer.from(resp.data);
  } catch { /* fall through */ }

  // Fallback: return HTML as text file if PDF fails
  return null;
};

module.exports = {
  name: 'pdf',
  aliases: ['makepdf', 'genpdf', 'project'],
  description: 'Generate a project PDF — school project, assignment, report',
  category: 'free',
  execute: async ({ sock, msg, from, sender, args, reply }) => {
    const userId  = sender.split('@')[0];
    const premium = database.isPremium(userId);
    database.logCommand(sender, 'pdf');

    // Parse: .pdf project "My Title" | Biology | My content here
    const fullText = args.join(' ');
    const type     = (args[0] || 'project').toLowerCase();

    // All PDF types are free — no premium gate

    // Parse title | subject | content (pipe-separated)
    const parts   = fullText.replace(type, '').trim().split('|').map(s => s.trim());
    const title   = parts[0] || 'My School Project';
    const subject = parts[1] || 'General';
    const rawContent = parts[2] || '';

    await reply(`📄 *Generating your PDF...*\n\nTitle: ${title}\nSubject: ${subject}\n\nPlease wait...`);
    await sock.sendPresenceUpdate('composing', from);

    try {
      // Generate content via AI if none provided
      const profile = database.getProfile(userId);
      let content   = rawContent;

      if (!content || content.length < 20) {
        const context = profile ? `Student: ${profile.name}, Age: ${profile.age}, School: ${profile.school}.` : '';
        const system  = `You are NovaSpark, a brilliant academic writer. ${context}
Write a complete school ${type} on the given topic.
Structure it with HTML headings (<h2>) for sections: Introduction, Main Body (3 sections), Conclusion, References.
Use <p> for paragraphs. Make it thorough and academic. Around 600-800 words.`;
        content = await APIs.chatAI(`Write a ${type} on: "${title}" (Subject: ${subject})`, system);
        // Clean up markdown that might come back
        content = content
          .replace(/^#+\s+(.+)$/gm, '<h2>$1</h2>')
          .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
          .replace(/\n\n/g, '</p><p>')
          .replace(/^([^<].+)$/gm, '<p>$1</p>');
      }

      const profile2 = database.getProfile(userId);
      const html     = buildHTML(type, { title, subject, content }, profile2);
      const pdfBuf   = await htmlToPdf(html);

      const tmpDir  = '/tmp/novaspark_pdf';
      if (!fs.existsSync(tmpDir)) fs.mkdirSync(tmpDir, { recursive: true });
      const safeTitle = title.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30);
      const tmpPath = path.join(tmpDir, `${safeTitle}_${Date.now()}.pdf`);

      if (pdfBuf && pdfBuf.length > 500) {
        fs.writeFileSync(tmpPath, pdfBuf);
        await sock.sendMessage(from, {
          document: { url: `file://${tmpPath}` },
          mimetype: 'application/pdf',
          fileName: `${safeTitle}.pdf`,
          caption:  `📄 *${title}*\n✅ PDF generated by NovaSpark Bot ⚡`,
        }, { quoted: msg });
        // Cleanup after 60s
        setTimeout(() => { try { fs.unlinkSync(tmpPath); } catch {} }, 60000);
      } else {
        // Fallback: send as text document
        const txtPath = tmpPath.replace('.pdf', '.txt');
        const plainText = html.replace(/<[^>]+>/g, '').replace(/\s{2,}/g, '\n').trim();
        fs.writeFileSync(txtPath, plainText);
        await sock.sendMessage(from, {
          document: { url: `file://${txtPath}` },
          mimetype: 'text/plain',
          fileName: `${safeTitle}.txt`,
          caption:  `📄 *${title}*\n_PDF conversion unavailable — sent as text file._\nContent generated by NovaSpark Bot ⚡`,
        }, { quoted: msg });
        setTimeout(() => { try { fs.unlinkSync(txtPath); } catch {} }, 60000);
      }
    } catch (err) {
      console.error('[PDF] Error:', err.message);
      await reply('❌ PDF generation failed. Try: *.pdf project My Title | Subject | Optional content*');
    }
  },
};
